const books ={
 geneza:'Geneza',
 exodul:'Exodul',
 leveticul:'Leveticul',
 numeri:'Numeri',
 deutoronomul:'Deutoroomul',
 iosua:'Iosua',
 judecatorii:'Judecatorii',
 rut:'Rut',
 intaiSamuel:'1 Samuel',
 doiSamuel:'2 Samuel',
 intaiImparati:'1 Imparati',
 doiImparati:'2 Imparati',
 intaiCronici: '1 Cronici',
 doiCronici:'2 Cronici',
 ezra:'Ezra',
 neemia:'Neemia',
 estera:'Estera',
 iov:'Iov',
 psalmii:'Psalmii',
 proverbe:'Proverbe',
 ecleseastrul:'Ecleseastrul',
 carteaCantarilor:'Cartea Cantarilor',
 isaia:'Isaia',
 ieremia:'Ieremia',
 plangerileIeremia:'Plangerile lui Ieremia',
 ezechel:'Ezechel',
 daniel:'Daniel',
 osea:'Osea',
 ioel:'Ioel',
 amos:'Amos',
 obadia:'Obadia',
 iona:'Iona',
 mica:'Mica',
 naum:'Naum',
 habacuc:"habacuc",
 tefania:'Tefania',
 hagai:'Hagai',
 zaharia:'Zaharia',
 maleahi:'Maleahi',
 matei:'Matei',
 marcu:'Marcu',
 luca:'Luca',
 ioan:'Ioan',
 fapteleApostolilor:'Faptele Apostolilor',
 romani:'Romani',
 intaiCorinteni:'1 Corinteni',
 doiCorinteni:'2 Corinteni',
 galateni:'Galateni',
 efeseni:"Efeseni",
 filipeni:'Filipeni',
 coloseni:'Coloseni',
 intaiTesaloniceni:'1 Tesaloniceni',
 doiTesaloniceni:'2 Tesaloniceni',
 intaiTimotei:'1 Timotei',
 doiTimotei:'2 Timotei',
 tit:'Tit',
 filimon:'Filimon',
 evrei:'Evrei',
 iacov:'Iacov',
 intaiPetru:'1 Petru',
 doiPetru:'2 Petru',
 intaiIoan:'1 Ioan',
 doiIoan:'2 Ioan',
 treiIoan:'3 Ioan',
 iuda:'Iuda',
 apocalipsa:'Apocalipsa'
}
export default books